site_name: bitpushr.net Plex Docs # Replace with your site name
site_url: https://docs.bitpushr.net # Replace with your site URL
theme:
  name: material
  logo: assets/images/bp_smol_1440.png # Replace with your logo
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

nav:
  - Welcome: index.md
  - What is Plex?: what-is-plex.md
  - Is Plex safe to use?: plex-safety.md
  - Getting Started:
    - Welcome: getting-started/index.md
    - Getting Plex: getting-started/getting-plex.md
    - Changing Plex streaming quality: getting-started/changing-stream-quality.md
    - Pinning Libraries: getting-started/pinning-libraries.md
    - Disabling Online Media Sources: getting-started/disabling-online-media-sources.md
    - Requesting Content with Overseerr: getting-started/overseerr.md
    - Getting Finished: getting-started/closing-out.md
  - Content Editions: content-editions.md
  - Managing Newsletter Subscriptions: unsubscribe-from-plex-newsletter.md
  - FAQ:
    - What is transcoding?: faq/what-is-transcoding.md
    - My video won't stop buffering: faq/wont-stop-buffering.md
    - Help, I forgot my Plex password!: faq/forgot-password.md
    - How do I add items to my Plex Universal Watchlist?: faq/adding-to-universal-watchlist.md
    - Responsible Content Requesting: faq/responsible-content-requests.md
    - Where is my requested content?: faq/missing-requests.md
    - What Are Content Editions? faq/content-editions.md
    - Content or Playback Issues: faq/content-issues.md
    - Content Quality and Language Options: faq/special-requests.md
    - I don't want to use this request thing, can't I just tell you what I want?: faq/i-dont-want-to-use-overseerr.md
    - Can I share your Plex server with someone else?: faq/can-i-share-your-plex.md
    - Technical Guide On Why Bitrate Matters: faq/why-bitrate-matters.md
    - Do I Need to Buy the Plex App: faq/do-i-buy-plex-app.md
  - Useful Links: useful-links.md
  - ↪ Logout: javascript:window.location.href='/auth/logout'

plugins:
  - search
  - mkdocs-video
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: bitpushr/plexdocs # Replace with your repo
      branch: main # Or your default branch
      exclude_committers:
        - "MisterCalvin"
        - "web-flow"  # GitHub web UI edits
        - "actions-user"  # GitHub Actions
        - "github-actions[bot]"  # GitHub Actions bot
      token: !ENV GITHUB_TOKEN

markdown_extensions:
  - toc:
      toc_depth: 1
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2025 bitpushr.net # Replace with your name

extra_css:
  - assets/css/extra.css

# Update/Remove all of your socials
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bitpushr
      name: bitpushr
    - icon: fontawesome/solid/globe
      link: https://bitpushr.net
      name: bitpushr.net
